[package]
name = "weather"
version = "0.1.0"
authors = ["Matt Potok <potok@mattpotok.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.10"
reqwest = "0.9.22"
serde = "1.0.103"
serde_json = "1.0.44"
serde_yaml = "0.8.11"
