[package]
name = "battery"
version = "0.1.0"
authors = ["Matt Potok <potok@mattpotok.com>"]
edition = "2018"

[dependencies]
approx = "0.3.2"
log = "0.4.8"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8.11"
simplelog = "0.7.4"
